version: '2' 
 
services: 
 
  redis: 
    image: redis:latest 
    container_name: redis 
    restart: always 
    volumes: 
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf  
      - ./redis/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf 
    network_mode: "host" 
 
  sentinel: 
    image: redis:latest 
    container_name: sentinel 
    restart: always 
    volumes: 
      - ./redis/sentinel.conf:/usr/local/etc/redis/sentinel.conf 
    command: redis-server /usr/local/etc/redis/sentinel.conf --sentinel 
    network_mode: "host" 
    depends_on: 
      - redis 