version: '2' 
 
services: 
 
  redis: 
    image: redis:latest 
    container_name: redis 
    restart: always 
    volumes: 
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf  
      - ./redis/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf 
    network_mode: "host" 
 
  sentinel: 
    image: redis:latest 
    container_name: sentinel 
    restart: always 
    volumes: 
      - ./redis/sentinel.conf:/usr/local/etc/redis/sentinel.conf 
    command: redis-server /usr/local/etc/redis/sentinel.conf --sentinel 
    network_mode: "host" 
    depends_on: 
      - redis 

  nginx:
    image: local-nginx-docker-python3
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/checkMaster.py:/etc/nginx/checkMaster.py
    command: bash -c "nginx -c /etc/nginx/nginx.conf && python3 -u /etc/nginx/checkMaster.py" 
    network_mode: "host"
    depends_on:
      - redis

  haproxy: 
    image: haproxy:latest
    container_name: haproxy 
    restart: always 
    volumes: 
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg 
    command: bash -c "haproxy -f /usr/local/etc/haproxy/haproxy.cfg -d"
    network_mode: "host"
    depends_on: 
      - redis